apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cognaioinsight.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
    {{- with .Values.cognaioinsight.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.cognaioinsight.autoscaling.enabled }}
  replicas: {{ .Values.cognaioinsight.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
      {{- with .Values.cognaioinsight.podSelectorLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with (merge (.Values.cognaioinsight.podAnnotations | default dict) (.Values.podAnnotations | default dict)) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cognaio.labels" . | nindent 8 }}
        {{- with (merge (.Values.cognaioinsight.podLabels | default dict) (.Values.podLabels | default dict)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.cognaioinsight.serviceAccount.name }}
      {{- with (default .Values.podSecurityContext .Values.cognaioinsight.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ default .Values.image.restartPolicy .Values.cognaioinsight.restartPolicy | default "Always" }}
      containers:
        - name: {{ .Values.cognaioinsight.name }}
          image: {{ .Values.image.containerRegistry }}/{{ .Values.cognaioinsight.image.name }}:{{ .Values.cognaioinsight.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with (default .Values.securityContext .Values.cognaioinsight.securityContext ) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.cognaioinsight.env.port }}
            protocol: TCP
          {{- with (default .Values.livenessProbe .Values.cognaioinsight.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default .Values.readinessProbe .Values.cognaioinsight.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cognaioinsight.extraEnv }}
          env:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/assets/configs.json
              subPath: configs.json
              name: config
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: config
          {{- with .Values.cognaioinsight.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
          {{- with .Values.cognaioinsight.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cognaioinsight.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: cognaioinsight-configs
      {{- with .Values.cognaioinsight.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.cognaioinsight.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cognaioinsight.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cognaioinsight.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}