apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
    {{- with .Values.nginx.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.nginx.autoscaling.enabled }}
  replicas: {{ .Values.nginx.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
      {{- with .Values.nginx.podSelectorLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with (merge (.Values.nginx.podAnnotations | default dict) (.Values.podAnnotations | default dict)) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cognaio.labels" . | nindent 8 }}
        {{- with (merge (.Values.nginx.podLabels | default dict) (.Values.podLabels | default dict)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.nginx.serviceAccount.name }}
      {{- with (default .Values.podSecurityContext .Values.nginx.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ default .Values.image.restartPolicy .Values.nginx.restartPolicy | default "Always" }}
      containers:
        - name: {{ .Values.nginx.name }}
          image: {{ .Values.image.containerRegistry }}/{{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with (default .Values.securityContext .Values.nginx.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.nginx.env.port }}
            protocol: TCP
          {{- with (default .Values.livenessProbe .Values.nginx.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default .Values.readinessProbe .Values.nginx.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nginx.extraEnv }}
          env:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.nginx.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nginx.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: config
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: confd-nginx.conf
              name: config
          {{- with .Values.nginx.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
      volumes:
        - name: config
          configMap:
            name: idp-nginx-config
      {{- with .Values.nginx.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}