apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.emailservice.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
    {{- with .Values.emailservice.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.emailservice.autoscaling.enabled }}
  replicas: {{ .Values.emailservice.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
      {{- with .Values.emailservice.podSelectorLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with (merge (.Values.emailservice.podAnnotations | default dict) (.Values.podAnnotations | default dict)) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cognaio.labels" . | nindent 8 }}
        {{- with (merge (.Values.emailservice.podLabels | default dict) (.Values.podLabels | default dict)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.emailservice.serviceAccount.name }}
      {{- with (default .Values.podSecurityContext .Values.emailservice.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ default .Values.image.restartPolicy .Values.emailservice.restartPolicy | default "Always" }}
      containers:
        - name: {{ .Values.emailservice.name }}
          image: {{ .Values.image.containerRegistry }}/{{ .Values.emailservice.image.name }}:{{ .Values.emailservice.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with (default .Values.securityContext .Values.emailservice.securityContext ) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.emailservice.env.port }}
            protocol: TCP
          {{- with (default .Values.livenessProbe .Values.emailservice.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default .Values.readinessProbe .Values.emailservice.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          - name: PORT
            value: {{ .Values.emailservice.env.port | quote }}  
          - name: LogSeverity
            value: {{ .Values.emailservice.env.logSeverity }}
          - name: PassPhrase_Crypto_Symetric_AppKey
            valueFrom:
              secretKeyRef:
                name: {{ .Values.emailservice.env.secret.name }}
                key: passPhraseCryptoSymetricAppKey
          {{- with .Values.emailservice.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.emailservice.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.emailservice.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with .Values.emailservice.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
      volumes:
      {{- with .Values.emailservice.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.emailservice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emailservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emailservice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}