apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.usermanual.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.usermanual.name }}
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.usermanual.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.usermanual.name }}
        appgroup: cognaio-idp
        {{- include "cognaio.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Values.usermanual.name }}
        image: {{ .Values.image.containerRegistry }}/{{ .Values.usermanual.image.name }}:{{ .Values.usermanual.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
           {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        {{- if .Values.usermanual.resources }}
        resources: {{- toYaml .Values.usermanual.resources | nindent 12 }}
        {{- end }}