{{- if .Values.cognaioflexsearchservice.env.secret.init -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cognaioflexsearchservice.env.secret.name }}
type: Opaque
data:
  passPhrase: {{ .Values.cognaioflexsearchservice.env.passPhrase_Repositories | b64enc | quote }}
  postgreSqlUser: {{ .Values.cognaioflexsearchservice.env.db.postgreSqlUser | b64enc | quote }}
  postgreSqlPwd: {{ .Values.cognaioflexsearchservice.env.db.postgreSqlPwd | b64enc | quote }}
  postgreSqlDbServer: {{ .Values.cognaioflexsearchservice.env.db.postgreSqlDbServer | b64enc | quote }}
{{- end }}