apiVersion: v1
kind: ConfigMap
metadata:
  name: cognaiostudio-configs
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
data:
  configs.json: |
    {
        "general": {
            "site": { "key": "BE8A9403-2079-3512-A46E-74253ED7F60F" },
            "defaultPreferences": {
                "language": "de"
            },
            "copyRight": "Copyright 2025 DTI",
            "version": "2.4.0"
        },
        "endpoints": {
            "analysis": "{{ .Values.cognaio.protocol }}://{{ .Values.cognaio.url }}/extraction/api"
        }
    }
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        server {
            listen 80;
            server_name localhost;

            root   /usr/share/nginx/html;
            index  index.html index.htm;
            include /etc/nginx/mime.types;

            gzip on;
            gzip_min_length 1000;
            gzip_proxied expired no-cache no-store private auth;
            gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

            # Add Content-Security-Policy for frame-ancestors
            add_header Content-Security-Policy "frame-ancestors 'self';";

            location / {
                try_files $uri $uri/ /index.html;
            }

            location /cceusermanual_images/ {
                proxy_pass {{ .Values.cognaio.protocol }}://{{ .Values.cognaio.url }}/extraction/api/app/usermanual/static/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }