apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cognaioapp.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.cognaioapp.name }}
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.cognaioapp.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.cognaioapp.name }}
        appgroup: cognaio-idp
        {{- include "cognaio.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.cognaioapp.name }}
        image: {{ .Values.image.containerRegistry }}/{{ .Values.cognaioapp.image.name }}:{{ .Values.cognaioapp.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
           {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: {{ .Values.cognaioapp.env.node_env }} 
        volumeMounts:
        - mountPath: /usr/share/nginx/html/assets/configs.json
          subPath: configs.json
          name: config
      volumes:
      - configMap:
          name: cognaioapp-configs  
        name: config
#        readinessProbe:
#          httpGet:
#            path: /manage/health/readiness
#            port: 8080
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
#          periodSeconds: 60
#          failureThreshold: 2
#        livenessProbe:
#          httpGet:
#            path: /manage/health/liveness
#            port: 8080
#          initialDelaySeconds: 20
#          timeoutSeconds: 5
#          periodSeconds: 60
#          failureThreshold: 1