apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cognaiostudio.service.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
    app: cognaio-idp
    name: {{ .Values.cognaiostudio.service.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.cognaiostudio.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "cognaio.selectorLabels" . | nindent 4 }}
    name: {{ .Values.cognaiostudio.name }}
  type: {{ .Values.cognaiostudio.service.type }}