{{- if .Values.cognaioservice.env.secret.init -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cognaioservice.env.secret.name }}
type: Opaque
data:
  postgreSqlUser: {{ .Values.cognaioservice.env.db.postgreSqlUser | b64enc | quote }}
  postgreSqlPwd: {{ .Values.cognaioservice.env.db.postgreSqlPwd | b64enc | quote }}
  #
  passPhraseAuditArtifacts: {{ .Values.cognaioservice.env.tokens.passPhraseAuditArtifacts | b64enc | quote }}
  passPhraseDefinitions: {{ .Values.cognaioservice.env.tokens.passPhraseDefinitions | b64enc | quote }}
  passPhraseTemplates: {{ .Values.cognaioservice.env.tokens.passPhraseTemplates | b64enc | quote }}
  #
  passPhraseCryptoAsymetric: {{ .Values.cognaioservice.env.tokens.passPhraseCryptoAsymetric | b64enc | quote }}
  passPhraseCryptoSymetric: {{ .Values.cognaioservice.env.tokens.passPhraseCryptoSymetric | b64enc | quote }}
  tokenEncryptionTokenJwtKey: {{ .Values.cognaioservice.env.tokens.tokenEncryptionTokenJwtKey | b64enc | quote }}
  passPhraseAccessTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseAccessTokenJwtKey | b64enc | quote }}
  passPhraseRefreshTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseRefreshTokenJwtKey | b64enc | quote }}
  passPhraseUnsubscribeTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseUnsubscribeTokenJwtKey | b64enc | quote }}
  passPhraseExportTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseExportTokenJwtKey | b64enc | quote }}
  passPhraseMailboxesTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseMailboxesTokenJwtKey | b64enc | quote }}
  passPhraseEnvelopesTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseEnvelopesTokenJwtKey | b64enc | quote }}
  #
  passPhraseRegisterTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseRegisterTokenJwtKey | b64enc | quote }}
  passPhraseOtpTokenJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseOtpTokenJwtKey | b64enc | quote }}
  #
  passPhraseAppKeyJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseAppKeyJwtKey | b64enc | quote }}
  passPhraseCryptoSymetricAppKey: {{ .Values.cognaioservice.env.tokens.passPhraseCryptoSymetricAppKey | b64enc | quote }}
  #
  passPhraseAnalyzeFromContentJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseAnalyzeFromContentJwtKey | b64enc | quote }}
  #
  mailAccountUser: {{ .Values.cognaioservice.env.mailAccount.user | b64enc | quote }}
  mailAccountPassword: {{ .Values.cognaioservice.env.mailAccount.password | b64enc | quote }}
  #
  passPhraseAnalyzeResponseDownloadJwtKey: {{ .Values.cognaioservice.env.tokens.passPhraseAnalyzeResponseDownloadJwtKey | b64enc | quote }}
  #
  apikeyAzureOpenAi: {{ .Values.cognaioservice.env.ai.apikeyAzureOpenAi | b64enc | quote }}
  apikeyNativeOpenAi: {{ .Values.cognaioservice.env.ai.apikeyNativeOpenAi | b64enc | quote }}
  apikeyAzureAiDocumentIntelligence: {{ .Values.cognaioservice.env.ai.apikeyAzureAiDocumentIntelligence | b64enc | quote }}
  apikeyAzureCognitiveServicesComputervision: {{ .Values.cognaioservice.env.ai.apikeyAzureCognitiveServicesComputervision | b64enc | quote }}
  #
  apikeyNativeGemini: {{ .Values.cognaioservice.env.ai.apikeyNativeGemini | b64enc | quote }}
  apikeyNativeAnthropic: {{ .Values.cognaioservice.env.ai.apikeyNativeAnthropic | b64enc | quote }}
  apikeyNativeCerebral: {{ .Values.cognaioservice.env.ai.apikeyNativeCerebral | b64enc | quote }}
  #
  accesskeyIdAwsTextract: {{ .Values.cognaioservice.env.aws.accesskeyIdAwsTextract | b64enc | quote }}
  secretAccessKeyAwsTextract: {{ .Values.cognaioservice.env.aws.secretAccessKeyAwsTextract | b64enc | quote }}
  accesskeyIdAwsBedrock: {{ .Values.cognaioservice.env.aws.accesskeyIdAwsBedrock | b64enc | quote }}
  secretAccessKeyAwsBedrock: {{ .Values.cognaioservice.env.aws.secretAccessKeyAwsBedrock | b64enc | quote }}
  {{- end }}