{{- if .Values.cognaio.cert.secret.init -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cognaio.cert.secret.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
    app: cognaio-idp
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.cognaio.cert.certificate | b64enc | quote }}
  tls.key: {{ .Files.Get .Values.cognaio.cert.key | b64enc | quote }}
{{- end }}