{{- if .Values.cognaioauditscleanup.env.secret.init -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cognaioauditscleanup.env.secret.name }}
type: Opaque
data:
  postgreSqlUser: {{ .Values.cognaioauditscleanup.env.db.postgreSqlUser | b64enc | quote }}
  postgreSqlPwd: {{ .Values.cognaioauditscleanup.env.db.postgreSqlPwd | b64enc | quote }}
{{- end }}