apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cognaioflexsearchservice.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.cognaioflexsearchservice.name }}
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.cognaioflexsearchservice.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.cognaioflexsearchservice.name }}
        appgroup: cognaio-idp
        {{- include "cognaio.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Values.cognaioflexsearchservice.name }}
        image: {{ .Values.image.containerRegistry }}/{{ .Values.cognaioflexsearchservice.image.name }}:{{ .Values.cognaioflexsearchservice.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
           {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: {{ .Values.cognaioflexsearchservice.env.port }}
        env:
        - name: PORT
          value: {{ .Values.cognaioflexsearchservice.env.port | quote }} 
        - name: NODE_ENV
          value: {{ .Values.cognaioflexsearchservice.env.node_env }} 
        - name: PostgreSql_User
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioflexsearchservice.env.secret.name }}
              key: postgreSqlUser
        - name: PostgreSql_Pwd
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioflexsearchservice.env.secret.name }}
              key: postgreSqlPwd
        - name: PostgreSql_Db_Server
          value: {{ .Values.cognaioflexsearchservice.env.db.postgreSqlDbServer }}:{{ .Values.cognaioflexsearchservice.env.db.postgreSqlDbPort }}
        - name: PostgreSql_Schemas
          value: {{ .Values.cognaioflexsearchservice.env.db.schemas }}
        - name: PostgreSql_Db_Name
          value: {{ .Values.cognaioflexsearchservice.env.db.postgreSqlDbName | quote }} 
        - name: PostgreSql_Ssl_Required
          value: {{ .Values.cognaioflexsearchservice.env.db.postgreSqlSslRequired | quote }} 
        - name: LogSeverity
          value: {{ .Values.cognaioflexsearchservice.env.logSeverity }}
        - name: PassPhrase_Repositories
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioflexsearchservice.env.secret.name }}
              key: passPhrase
        {{- if .Values.cognaioflexsearchservice.resources }}
        resources: {{- toYaml .Values.cognaioflexsearchservice.resources | nindent 12 }}
        {{- end }}