apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cognaioservice.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.cognaioservice.name }}
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.cognaioservice.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.cognaioservice.name }}
        appgroup: cognaio-idp
        {{- include "cognaio.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
# Database Schema Manager Init container
      initContainers:
      - name: init-cognaio-schema-manager
        image: {{ .Values.image.containerRegistry }}/{{ .Values.cognaioservice.init.image.name }}:{{ .Values.cognaioservice.init.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: COGNAIOENVIRONMENTVARIABLES__ENVIRONMENTNAMESPACE
          value: {{ .Values.cognaio.namespace | quote }}
        - name: COGNAIOENVIRONMENTVARIABLES__ORGANIZATIONUSERS
          value: {{ .Values.cognaioservice.env.organization.users | quote }}
        - name: COGNAIOENVIRONMENTVARIABLES__DBNAME
          value: {{ .Values.cognaioservice.env.db.postgreSqlDbName | quote }} 
        - name: COGNAIOENVIRONMENTVARIABLES__DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name}}
              key: postgreSqlPwd
        - name: COGNAIOENVIRONMENTVARIABLES__DBUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: postgreSqlUser
        - name: COGNAIOENVIRONMENTVARIABLES__DBSERVER
          value: {{ .Values.cognaioservice.env.db.postgreSqlDbServer | quote }}
        - name: COGNAIOENVIRONMENTVARIABLES__DBPORT
          value: {{ .Values.cognaioservice.env.db.postgreSqlDbPort | quote }}
        - name: COGNAIOENVIRONMENTVARIABLES__PASSPHRASETEMPLATES
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseTemplates
        - name: COGNAIOENVIRONMENTVARIABLES__PASSPHRASEDEFINITIONS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseDefinitions
        - name: COGNAIOENVIRONMENTVARIABLES__APIKEYAZUREOPENAI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: apikeyAzureOpenAi
        - name: COGNAIOENVIRONMENTVARIABLES__APIKEYNATIVEOPENAI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: apikeyNativeOpenAi
        - name: COGNAIOENVIRONMENTVARIABLES__APIKEYAZUREAIDOCUMENTINTELLIGENCE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: apikeyAzureAiDocumentIntelligence
        - name: COGNAIOENVIRONMENTVARIABLES__APIKEYAZURECOGNITIVESERVICESCOMPUTERVISION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: apikeyAzureCognitiveServicesComputervision
        - name: COGNAIOENVIRONMENTVARIABLES__ENDPOINTAZUREOPENAI
          value: {{ .Values.cognaioservice.env.ai.endpointAzureOpenAi | quote }}
        - name: COGNAIOENVIRONMENTVARIABLES__ENDPOINTNATIVEOPENAI
          value: {{ .Values.cognaioservice.env.ai.endpointNativeOpenAi | quote }}
        - name: COGNAIOENVIRONMENTVARIABLES__ENDPOINTAZUREAIDOCUMENTINTELLIGENCE
          value: {{ .Values.cognaioservice.env.ai.endpointAzureAiDocumentIntelligence | quote }}
        - name: COGNAIOENVIRONMENTVARIABLES__ENDPOINTAZURECOGNITIVESERVICESCOMPUTERVISION
          value: {{ .Values.cognaioservice.env.ai.endpointAzureCognitiveServicesComputerVision | quote }}
# Other LLMS
        - name: COGNAIOENVIRONMENTVARIABLES__APIKEYNATIVEGEMINI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: apikeyNativeGemini
        - name: COGNAIOENVIRONMENTVARIABLES__APIKEYNATIVEANTHROPIC
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: apikeyNativeAnthropic
        - name: COGNAIOENVIRONMENTVARIABLES__APIKEYNATIVECEREBRAL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: apikeyNativeCerebral
        - name: COGNAIOENVIRONMENTVARIABLES__ENDPOINTNATIVECEREBRAL
          value: {{ .Values.cognaioservice.env.ai.endpointNativeCerebral | quote }}
# AWS Settings
    # AWS Textract
        - name: COGNAIOENVIRONMENTVARIABLES__ACCESSKEYIDAWSTEXTRACT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: accesskeyIdAwsTextract
        - name: COGNAIOENVIRONMENTVARIABLES__SECRETACCESSKEYAWSTEXTRACT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: secretAccessKeyAwsTextract
        - name: COGNAIOENVIRONMENTVARIABLES__REGIONAWSTEXTRACT
          value: {{ .Values.cognaioservice.env.aws.regionAwsTextract | quote }}
    # AWS Bedrock
        - name: COGNAIOENVIRONMENTVARIABLES__ACCESSKEYIDAWSBEDROCK
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: accesskeyIdAwsBedrock
        - name: COGNAIOENVIRONMENTVARIABLES__SECRETACCESSKEYAWSBEDROCK
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: secretAccessKeyAwsBedrock
        - name: COGNAIOENVIRONMENTVARIABLES__REGIONAWSBEDROCK
          value: {{ .Values.cognaioservice.env.aws.regionAwsBedrock | quote }}
# Main Container
      containers:
      - name: {{ .Values.cognaioservice.name }}
        image: {{ .Values.image.containerRegistry }}/{{ .Values.cognaioservice.image.name }}:{{ .Values.cognaioservice.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
           {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: {{ .Values.cognaioservice.env.port }}
        env:
        - name: PORT
          value: {{ .Values.cognaioservice.env.port | quote }}
        - name: NODE_ENV
          value: {{ .Values.cognaioservice.env.node_env }} 
        - name: BaseWebAppLink
          value: {{ .Values.cognaio.protocol }}://{{ .Values.cognaio.url }}{{ .Values.cognaiostudio.service.urlpath }}
        - name: BaseCognaioServiceUrl
          value: {{ .Values.cognaio.protocol }}://{{ .Values.cognaio.url }}{{ .Values.cognaioservice.service.urlpath }}
        - name: BaseUrl_FlexSearchProvider
          value: http://{{ .Values.cognaioflexsearchservice.service.name }}
        - name: BaseUrl_ImageProvider
          value: http://{{ .Values.imageprovider.service.name }}
        - name: BaseUrl_EmailProvider
          value: http://{{ .Values.emailservice.service.name }}
        - name: BaseUrl_ObjectDetectionProvider
          value: http://{{ .Values.objectdetectionprovider.service.name }}
        - name: BaseUrl_UserManual
          value: http://{{ .Values.nginx.service.name }}/usermanual
        - name: RedisProviderUrl
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.secret.name }}
              key: providerUrl
# DB
        - name: PostgreSql_User
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: postgreSqlUser
        - name: PostgreSql_Pwd
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: postgreSqlPwd
        - name: PostgreSql_Db_Server
          value: {{ .Values.cognaioservice.env.db.postgreSqlDbServer }}:{{ .Values.cognaioservice.env.db.postgreSqlDbPort }}
        - name: PostgreSql_Ssl_Required
          value: {{ .Values.cognaioservice.env.db.postgreSqlSslRequired | quote }}
        - name: PostgreSql_Db_Name
          value: {{ .Values.cognaioservice.env.db.postgreSqlDbName | quote }} 
        - name: PostgreSql_Schemas
          value: {{ .Values.cognaioservice.env.db.schemas }}
# Tokens
        - name: PassPhrase_AuditArtifacts
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseAuditArtifacts
        - name: PassPhrase_Definitions
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseDefinitions
        - name: PassPhrase_Templates
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseTemplates
#
        - name: PassPhrase_Crypto_Asymetric
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseCryptoAsymetric
        - name: PassPhrase_Crypto_Symetric
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseCryptoSymetric
        - name: Token_EncryptionToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: tokenEncryptionTokenJwtKey
        - name: PassPhrase_AccessToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseAccessTokenJwtKey
        - name: PassPhrase_RefreshToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseRefreshTokenJwtKey
        - name: PassPhrase_UnsubscribeToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseUnsubscribeTokenJwtKey
        - name: PassPhrase_ExportToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseExportTokenJwtKey
        - name: PassPhrase_MailboxesToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseMailboxesTokenJwtKey
        - name: PassPhrase_EnvelopesToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseEnvelopesTokenJwtKey
#
        - name: PassPhrase_RegisterToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseRegisterTokenJwtKey
        - name: PassPhrase_OtpToken_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseOtpTokenJwtKey
#
        - name: PassPhrase_AppKey_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseAppKeyJwtKey
        - name: PassPhrase_Crypto_Symetric_AppKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseCryptoSymetricAppKey
#
        - name: PassPhrase_AnalyzeFromContent_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseAnalyzeFromContentJwtKey
        - name: PassPhrase_AnalyzeResponse_Download_JwtKey
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: passPhraseAnalyzeResponseDownloadJwtKey
# Mailbox Account
        - name: MailAccount_Host
          value: {{ .Values.cognaioservice.env.mailAccount.host | quote }} 
        - name: MailAccount_Port
          value: {{ .Values.cognaioservice.env.mailAccount.port | quote }}
        - name: MailAccount_User
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: mailAccountUser
        - name: MailAccount_Pwd
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cognaioservice.env.secret.name }}
              key: mailAccountPassword
        - name: MailAccount_FromAddressFriendlyName
          value: {{ .Values.cognaioservice.env.mailAccount.fromAddressFriendlyName | quote }}
        - name: MailAccount_UseAdvancedAuth
          value: {{ .Values.cognaioservice.env.mailAccount.useAdvancedAuth | quote }}
        - name: MailAccount_AdvancedAuthJson
          value: {{ .Values.cognaioservice.env.mailAccount.advancedAuthJson | quote }}
        - name: MailAccount_UseCustomSettings
          value: {{ .Values.cognaioservice.env.mailAccount.useCustomSettings | quote }}
        - name: MailAccount_CustomSettingsJson
          value: {{ .Values.cognaioservice.env.mailAccount.customSettingsJson | quote }}
# Cognitive Services
        - name: AzureCognitiveServicesComputerVision_MaxRequestTimeoutInSec
          value: {{ .Values.cognaioservice.env.cognitiveServices.computervision.maxRequestTimeoutInSec | quote }} 
        - name: AzureCognitiveServicesComputerVision_MaxRetries
          value: {{ .Values.cognaioservice.env.cognitiveServices.computervision.maxRetries | quote }}
        - name: AzureCognitiveServicesComputerVision_MaxRetriesWaitTimeoutInSec
          value: {{ .Values.cognaioservice.env.cognitiveServices.computervision.maxRetriesWaitTimeoutInSec | quote }}
        - name: AzureCognitiveServicesComputerVision_MaxWaitTimeoutForFinishedInSec
          value: {{ .Values.cognaioservice.env.cognitiveServices.computervision.maxWaitTimeoutForFinishedInSec | quote }}
# Document Intelligence
        - name: AzureAiDocumentIntelligence_MaxRequestTimeoutInSec
          value: {{ .Values.cognaioservice.env.cognitiveServices.aiDocumentIntelligence.maxRequestTimeoutInSec | quote }}
        - name: AzureAiDocumentIntelligence_MaxRetries
          value: {{ .Values.cognaioservice.env.cognitiveServices.aiDocumentIntelligence.maxRetries | quote }}
        - name: AzureAiDocumentIntelligence_MaxRetriesWaitTimeoutInSec
          value: {{ .Values.cognaioservice.env.cognitiveServices.aiDocumentIntelligence.maxRetriesWaitTimeoutInSec | quote }}
# AWS Textract
        - name: AwsTextract_MaxRequestTimeoutInSec
          value: {{ .Values.cognaioservice.env.cognitiveServices.awsTextract.maxRequestTimeoutInSec | quote }}
        - name: AwsTextract_MaxRetries
          value: {{ .Values.cognaioservice.env.cognitiveServices.awsTextract.maxRetries | quote }}
        - name: AwsTextract_MaxRetriesWaitTimeoutInSec
          value: {{ .Values.cognaioservice.env.cognitiveServices.awsTextract.maxRetriesWaitTimeoutInSec | quote }}
# Essentials
        - name: Essential_Warning_Notification_TimeoutInHours
          value: {{ .Values.cognaioservice.env.essentials.warningNotificationTimeoutInHours | quote }}
        - name: Essential_FeatureExceedsLimits_Notification_TimeoutInDays
          value: {{ .Values.cognaioservice.env.essentials.featureExceedsLimitsNotificationTimeoutInDays | quote }}
# Other
        - name: LogSeverity
          value: {{ .Values.cognaioservice.env.logSeverity }}
        - name: EnvironmentNameForNotifications
          value: {{ .Values.cognaioservice.env.environmentNameForNotifications }}
# Preview Features
        - name: Feature_Preview_Ui_Ai_Chain_Crafter_Disabled
          value: {{ .Values.cognaioservice.env.featurePreview.uiAiChainCrafterDisabled | quote }}
        - name: Feature_Preview_Cerebral_Edge_Disabled
          value: {{ .Values.cognaioservice.env.featurePreview.cerebralEdgeDisabled | quote }}
        - name: Feature_Preview_Aws_Services_Disabled
          value: {{ .Values.cognaioservice.env.featurePreview.awsServicesDisabled | quote }}
        {{- if .Values.cognaioservice.resources }}
        resources: {{- toYaml .Values.cognaioservice.resources | nindent 12 }}
        {{- end }}