{{- if .Values.emailservice.env.secret.init -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.emailservice.env.secret.name }}
type: Opaque
data:
  passPhraseCryptoSymetricAppKey: {{ .Values.emailservice.env.passPhraseCryptoSymetricAppKey | b64enc | quote }}
{{- end }}