apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-nginx-config
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
data:
  nginx.conf: |
    #events { worker_connections 1024; }
    #upstream servers
    upstream cognaiostudios {
        server {{ .Values.cognaiostudio.service.name }};
    }

    upstream cognaiodocumentation {
        server {{ .Values.usermanual.service.name }};
    }

    upstream serviceproviderimages {
        server {{ .Values.imageprovider.service.name }};
    }

    upstream serviceprovideremails {
        server {{ .Values.emailservice.service.name }};
    }

    upstream serviceproviderflexsearches {
        server {{ .Values.cognaioflexsearchservice.service.name }};
    }
    
    upstream serviceproviderextractions {
        server {{ .Values.cognaioservice.service.name }};
    }

    upstream serviceproviderobjectdetection {
        server {{ .Values.objectdetectionprovider.service.name }};
    }
   
    map "$remote_addr-$request_uri" $block_this_request {
    default 0;
    ~^127\.0\.0\.1-/ 1;
    }

    server {
        listen 80;
        listen [::]:80;

        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;

        server_name {{ .Values.cognaio.url }};
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Proxying the connections
        location /usermanual/ {
            if ($block_this_request) { return 403; }
            client_max_body_size 150M;
            client_body_buffer_size 150M; 
            proxy_buffering off;
            proxy_pass http://cognaiodocumentation/cceUserManual/;
        }

        # # Proxying the connections
        # location /imageprovider/ {
        #     if ($block_this_request) { return 403; }
        #     client_max_body_size 150M;
        #     client_body_buffer_size 150M; 
        #     proxy_buffering off;
        #     proxy_pass http://serviceproviderimages/;
        # }

        # Proxying the connections
        location /extraction/ {
            proxy_set_header  Host $host;
            proxy_set_header  X-Real-IP $remote_addr;
            proxy_set_header  X-Forwarded-For $remote_addr;
            proxy_set_header  X-Forwarded-Host $remote_addr;
            client_max_body_size 250M;
            client_body_buffer_size 250M; 
            proxy_buffering off;
            proxy_pass http://serviceproviderextractions;
        }
        
        # Proxying the connections
        location /cognaioanalyze/ {
            proxy_set_header  Host $host;
            proxy_set_header  X-Real-IP $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  X-Forwarded-Host $host;
            client_max_body_size 150M;
            client_body_buffer_size 150M; 
            proxy_buffering off;
            proxy_pass http://cognaiostudios/;
        }

        # Proxying the connections
        location /objectdetectionprovider/ {
            if ($block_this_request) { return 403; }
            client_max_body_size 150M;
            client_body_buffer_size 150M; 
            proxy_buffering off;
            proxy_pass http://serviceproviderobjectdetection/;
        }

        location / {
            return 301 {{ .Values.cognaio.protocol }}://{{ .Values.cognaio.url }}$request_uri;
        }
    }