apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.objectdetectionprovider.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.objectdetectionprovider.name }}
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.objectdetectionprovider.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.objectdetectionprovider.name }}
        appgroup: cognaio-idp
        {{- include "cognaio.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Values.objectdetectionprovider.name }}
        image: {{ .Values.image.containerRegistry }}/{{ .Values.objectdetectionprovider.image.name }}:{{ .Values.objectdetectionprovider.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
           {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: {{ .Values.objectdetectionprovider.env.port }}
        env:
        - name: NODE_ENV
          value: production 
        {{- if .Values.objectdetectionprovider.resources }}
        resources: {{- toYaml .Values.objectdetectionprovider.resources | nindent 12 }}
        {{- end }}