apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.objectdetectionprovider.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.objectdetectionprovider.name }}
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.objectdetectionprovider.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.objectdetectionprovider.name }}
        appgroup: cognaio-idp
        {{- include "cognaio.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.objectdetectionprovider.name }}
        image: {{ .Values.image.containerRegistry }}/{{ .Values.objectdetectionprovider.image.name }}:{{ .Values.objectdetectionprovider.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
           {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: {{ .Values.objectdetectionprovider.env.port }}
        env:
        - name: NODE_ENV
          value: production 
        resources:
          request:
            memory: "512Mi"
          limits:
            memory: "5120Mi"


#        readinessProbe:
#          httpGet:
#            path: /manage/health/readiness
#            port: 8080
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
#          periodSeconds: 60
#          failureThreshold: 2
#        livenessProbe:
#          httpGet:
#            path: /manage/health/liveness
#            port: 8080
#          initialDelaySeconds: 20
#          timeoutSeconds: 5
#          periodSeconds: 60
#          failureThreshold: 1