{{- if .Values.redis.secret.init -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secret.name }}
type: Opaque
data:
  password: {{ .Values.redis.secret.password | b64enc | quote }}
  providerUrl: {{ .Values.redis.secret.providerUrl | b64enc | quote }}
{{- end }}