{{- if .Values.usermanual.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.usermanual.serviceAccount.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
  {{- with .Values.usermanual.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.usermanual.serviceAccount.automount }}
{{- end }}
