apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cognaioservice.service.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
    {{- with .Values.cognaioservice.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.cognaioservice.service.port }}
    protocol: TCP
    targetPort: {{ .Values.cognaioservice.env.port }} 
  selector:
    {{- include "cognaio.selectorLabels" . | nindent 4 }}
    {{- with .Values.cognaioservice.podSelectorLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  type: {{ .Values.cognaioservice.service.type }}