apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.objectdetectionprovider.name }}
  labels:
    {{- include "cognaio.labels" . | nindent 4 }}
    {{- with .Values.objectdetectionprovider.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.objectdetectionprovider.autoscaling.enabled }}
  replicas: {{ .Values.objectdetectionprovider.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cognaio.selectorLabels" . | nindent 6 }}
      {{- with .Values.objectdetectionprovider.podSelectorLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with (merge (.Values.objectdetectionprovider.podAnnotations | default dict) (.Values.podAnnotations | default dict)) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cognaio.labels" . | nindent 8 }}
        {{- with (merge (.Values.objectdetectionprovider.podLabels | default dict) (.Values.podLabels | default dict)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.objectdetectionprovider.serviceAccount.name }}
      {{- with (default .Values.podSecurityContext .Values.objectdetectionprovider.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ default .Values.image.restartPolicy .Values.objectdetectionprovider.restartPolicy | default "Always" }}
      containers:
        - name: {{ .Values.objectdetectionprovider.name }}
          image: {{ .Values.image.containerRegistry }}/{{ .Values.objectdetectionprovider.image.name }}:{{ .Values.objectdetectionprovider.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with (default .Values.securityContext .Values.objectdetectionprovider.securityContext ) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.objectdetectionprovider.env.port }}
            protocol: TCP
          {{- with (default .Values.livenessProbe .Values.objectdetectionprovider.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default .Values.readinessProbe .Values.objectdetectionprovider.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.objectdetectionprovider.extraEnv }}
          env:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.objectdetectionprovider.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.objectdetectionprovider.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with .Values.objectdetectionprovider.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
      {{- with .Values.objectdetectionprovider.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.objectdetectionprovider.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.objectdetectionprovider.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.objectdetectionprovider.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.objectdetectionprovider.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}